<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO2RoVGc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO2RoVGc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerO2RoVGc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerO2RoVGc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerO2RoVGc\App_KernelDevDebugContainer([
    'container.build_hash' => 'O2RoVGc',
    'container.build_id' => '15aaf09a',
    'container.build_time' => 1676986019,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO2RoVGc');
